---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: nginx
    run_list:
      - recipe[cloudburrito::nginx]
    attributes:
