---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: nginx
    run_list:
      - recipe[cloudburrito::nginx]
  - name: sshd
    run_list:
      - recipe[cloudburrito::sshd]
  - name: security
    run_list:
      - recipe[cloudburrito::security]
  - name: capistrano
    run_list:
      - recipe[cloudburrito::capistrano]
