---
provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: nginx
    driver: vagrant
    run_list:
      - recipe[cloudburrito::nginx]
  - name: sshd
    driver: vagrant
    run_list:
      - recipe[cloudburrito::sshd]
  - name: security
    driver: docker
    run_list:
      - recipe[cloudburrito::security]
  - name: deploy
    driver: docker
    run_list:
      - recipe[cloudburrito::deploy]
